import { customType, uuid, timestamp } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// pgvector. We don't use the helper from drizzle-orm-pg-vector because we want
// HNSW indexes via SQL and customType keeps the type signature explicit.
export const vector = (dimensions: number) =>
  customType<{ data: number[]; driverData: string }>({
    dataType() {
      return `vector(${dimensions})`;
    },
    toDriver(value) {
      return `[${value.join(",")}]`;
    },
    fromDriver(value) {
      return JSON.parse(value as string) as number[];
    },
  });

// Postgres tsvector. We let triggers / generated columns populate the value; the
// driver representation is opaque here.
export const tsvector = customType<{ data: string; notNull: false; default: false }>({
  dataType() {
    return "tsvector";
  },
});

// UUIDv7 PK helper. The actual UUID is generated by uuid-ossp / pgcrypto with a
// trigger or by the application; we just declare the column.
export const idPk = () =>
  uuid("id").primaryKey().default(sql`gen_random_uuid()`);

export const createdAt = () =>
  timestamp("created_at", { withTimezone: true }).notNull().defaultNow();

export const updatedAt = () =>
  timestamp("updated_at", { withTimezone: true }).notNull().defaultNow();

export const deletedAt = () => timestamp("deleted_at", { withTimezone: true });
