import {
  pgTable,
  uuid,
  text,
  integer,
  smallint,
  boolean,
  numeric,
  date,
  timestamp,
  jsonb,
  index,
  uniqueIndex,
  primaryKey,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createdAt, deletedAt, idPk, tsvector, updatedAt, vector } from "./columns.js";
import {
  barcodeSourceEnum,
  consumptionReasonEnum,
  dietEnum,
  ingestionEventKindEnum,
  ingestionEventStatusEnum,
  ingredientCategoryEnum,
  locationKindEnum,
  recipeEffortEnum,
  recipeHealthEnum,
  recipeSourceEnum,
  stockSourceEnum,
  storageUnitEnum,
} from "./enums.js";

export * from "./enums.js";

// ---------- Auth ----------

export const users = pgTable("users", {
  id: idPk(),
  email: text("email").notNull().unique(),
  password_hash: text("password_hash").notNull(),
  display_name: text("display_name"),
  created_at: createdAt(),
  updated_at: updatedAt(),
});

export const sessions = pgTable(
  "sessions",
  {
    id: text("id").primaryKey(),
    user_id: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expires_at: timestamp("expires_at", { withTimezone: true }).notNull(),
    created_at: createdAt(),
  },
  (t) => [index("sessions_user_id_idx").on(t.user_id)],
);

export const webauthnCredentials = pgTable("webauthn_credentials", {
  id: text("id").primaryKey(),
  user_id: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  public_key: text("public_key").notNull(),
  counter: integer("counter").notNull().default(0),
  device_name: text("device_name"),
  created_at: createdAt(),
  last_used_at: timestamp("last_used_at", { withTimezone: true }),
});

export const mcpTokens = pgTable(
  "mcp_tokens",
  {
    id: idPk(),
    user_id: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    hashed_token: text("hashed_token").notNull(),
    last_used_at: timestamp("last_used_at", { withTimezone: true }),
    revoked_at: timestamp("revoked_at", { withTimezone: true }),
    created_at: createdAt(),
  },
  (t) => [
    index("mcp_tokens_user_id_idx").on(t.user_id),
    uniqueIndex("mcp_tokens_hashed_token_idx").on(t.hashed_token),
  ],
);

// ---------- Ingredients ----------

export const ingredients = pgTable(
  "ingredients",
  {
    id: idPk(),
    user_id: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    canonical_name_de: text("canonical_name_de").notNull(),
    canonical_name_en: text("canonical_name_en"),
    category: ingredientCategoryEnum("category").notNull(),
    default_unit: storageUnitEnum("default_unit").notNull(),
    density_g_per_ml: numeric("density_g_per_ml", { precision: 8, scale: 4 }),
    typical_piece_weight_g: numeric("typical_piece_weight_g", { precision: 10, scale: 2 }),
    shelf_life_days: integer("shelf_life_days"),
    embedding: vector(1024)("embedding"),
    // tsvector generated by trigger using german_unaccent config (see migration).
    name_tsv: tsvector("name_tsv"),
    created_at: createdAt(),
    updated_at: updatedAt(),
  },
  (t) => [
    index("ingredients_user_id_idx").on(t.user_id),
    uniqueIndex("ingredients_user_canonical_idx").on(t.user_id, t.canonical_name_de),
    // GIN on name_tsv and HNSW on embedding declared in raw SQL migration.
  ],
);

export const ingredientAliases = pgTable(
  "ingredient_aliases",
  {
    id: idPk(),
    ingredient_id: uuid("ingredient_id")
      .notNull()
      .references(() => ingredients.id, { onDelete: "cascade" }),
    alias: text("alias").notNull(),
    lang: text("lang").notNull().default("de-CH"),
    source: text("source").notNull().default("user"),
    confidence: numeric("confidence", { precision: 4, scale: 3 }).notNull().default("1.000"),
    created_at: createdAt(),
  },
  (t) => [
    uniqueIndex("ingredient_aliases_unique_idx").on(t.ingredient_id, t.alias, t.lang),
    index("ingredient_aliases_alias_idx").on(t.alias),
    // pg_trgm GIN index declared in raw SQL migration.
  ],
);

// ---------- Barcodes ----------

export const barcodes = pgTable("barcodes", {
  gtin: text("gtin").primaryKey(),
  ingredient_id: uuid("ingredient_id").references(() => ingredients.id, { onDelete: "set null" }),
  brand: text("brand"),
  product_name: text("product_name"),
  package_quantity: numeric("package_quantity", { precision: 10, scale: 3 }),
  package_unit: storageUnitEnum("package_unit"),
  off_payload: jsonb("off_payload"),
  source: barcodeSourceEnum("source").notNull(),
  fetched_at: timestamp("fetched_at", { withTimezone: true }).notNull().defaultNow(),
});

// ---------- Locations & stock ----------

export const locations = pgTable(
  "locations",
  {
    id: idPk(),
    user_id: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    kind: locationKindEnum("kind").notNull(),
    display_order: integer("display_order").notNull().default(0),
    created_at: createdAt(),
  },
  (t) => [
    index("locations_user_id_idx").on(t.user_id),
    uniqueIndex("locations_user_name_idx").on(t.user_id, t.name),
  ],
);

export const stockItems = pgTable(
  "stock_items",
  {
    id: idPk(),
    user_id: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    ingredient_id: uuid("ingredient_id")
      .notNull()
      .references(() => ingredients.id, { onDelete: "restrict" }),
    location_id: uuid("location_id")
      .notNull()
      .references(() => locations.id, { onDelete: "restrict" }),
    quantity: numeric("quantity", { precision: 12, scale: 3 }).notNull(),
    unit: storageUnitEnum("unit").notNull(),
    original_quantity: numeric("original_quantity", { precision: 12, scale: 3 }),
    barcode: text("barcode").references(() => barcodes.gtin, { onDelete: "set null" }),
    purchased_at: date("purchased_at"),
    expiry_date: date("expiry_date"),
    opened_at: timestamp("opened_at", { withTimezone: true }),
    notes: text("notes"),
    confidence: numeric("confidence", { precision: 4, scale: 3 }).notNull().default("1.000"),
    source: stockSourceEnum("source").notNull(),
    source_event_id: uuid("source_event_id"),
    created_at: createdAt(),
    updated_at: updatedAt(),
    deleted_at: deletedAt(),
  },
  (t) => [
    index("stock_items_user_ingredient_location_idx").on(t.user_id, t.ingredient_id, t.location_id),
    index("stock_items_user_expiry_idx").on(t.user_id, t.expiry_date),
    index("stock_items_source_event_idx").on(t.source_event_id),
  ],
);

export const essentials = pgTable(
  "essentials",
  {
    id: idPk(),
    user_id: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    ingredient_id: uuid("ingredient_id")
      .notNull()
      .references(() => ingredients.id, { onDelete: "cascade" }),
    present: boolean("present").notNull().default(true),
    low: boolean("low").notNull().default(false),
    updated_at: updatedAt(),
  },
  (t) => [uniqueIndex("essentials_user_ingredient_idx").on(t.user_id, t.ingredient_id)],
);

// ---------- Consumption & usage ----------

export const consumptionEvents = pgTable(
  "consumption_events",
  {
    id: idPk(),
    user_id: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    stock_item_id: uuid("stock_item_id")
      .notNull()
      .references(() => stockItems.id, { onDelete: "cascade" }),
    ingredient_id: uuid("ingredient_id")
      .notNull()
      .references(() => ingredients.id, { onDelete: "restrict" }),
    quantity_consumed: numeric("quantity_consumed", { precision: 12, scale: 3 }).notNull(),
    unit: storageUnitEnum("unit").notNull(),
    reason: consumptionReasonEnum("reason").notNull().default("cooked"),
    recipe_id: uuid("recipe_id"),
    notes: text("notes"),
    occurred_at: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("consumption_user_ingredient_occurred_idx").on(t.user_id, t.ingredient_id, t.occurred_at),
    index("consumption_stock_idx").on(t.stock_item_id),
  ],
);

// ---------- Recipes ----------

export const recipes = pgTable(
  "recipes",
  {
    id: idPk(),
    user_id: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    summary: text("summary"),
    instructions_md: text("instructions_md").notNull(),
    effort: recipeEffortEnum("effort").notNull(),
    time_minutes: integer("time_minutes").notNull(),
    healthiness: recipeHealthEnum("healthiness").notNull(),
    cuisine: text("cuisine"),
    servings: integer("servings").notNull().default(2),
    source: recipeSourceEnum("source").notNull().default("ai"),
    source_url: text("source_url"),
    embedding: vector(1024)("embedding"),
    times_cooked: integer("times_cooked").notNull().default(0),
    last_cooked_at: timestamp("last_cooked_at", { withTimezone: true }),
    rating: smallint("rating"),
    created_at: createdAt(),
  },
  (t) => [index("recipes_user_idx").on(t.user_id)],
);

export const recipeIngredients = pgTable(
  "recipe_ingredients",
  {
    id: idPk(),
    recipe_id: uuid("recipe_id")
      .notNull()
      .references(() => recipes.id, { onDelete: "cascade" }),
    ingredient_id: uuid("ingredient_id").references(() => ingredients.id, {
      onDelete: "set null",
    }),
    raw_text: text("raw_text").notNull(),
    quantity: numeric("quantity", { precision: 12, scale: 3 }),
    unit: storageUnitEnum("unit"),
    optional: boolean("optional").notNull().default(false),
    note: text("note"),
  },
  (t) => [index("recipe_ingredients_recipe_idx").on(t.recipe_id)],
);

// ---------- Ingestion ----------

export const ingestionEvents = pgTable(
  "ingestion_events",
  {
    id: idPk(),
    user_id: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    kind: ingestionEventKindEnum("kind").notNull(),
    status: ingestionEventStatusEnum("status").notNull().default("pending"),
    input_blob_path: text("input_blob_path"),
    transcript: text("transcript"),
    llm_response: jsonb("llm_response"),
    error: text("error"),
    created_at: createdAt(),
    applied_at: timestamp("applied_at", { withTimezone: true }),
  },
  (t) => [index("ingestion_events_user_status_idx").on(t.user_id, t.status)],
);

export const ingestionProposals = pgTable(
  "ingestion_proposals",
  {
    id: idPk(),
    event_id: uuid("event_id")
      .notNull()
      .references(() => ingestionEvents.id, { onDelete: "cascade" }),
    proposed_action: jsonb("proposed_action").notNull(),
    chosen: boolean("chosen"),
    applied_stock_item_id: uuid("applied_stock_item_id").references(() => stockItems.id, {
      onDelete: "set null",
    }),
    created_at: createdAt(),
  },
  (t) => [index("ingestion_proposals_event_idx").on(t.event_id)],
);

// ---------- Preferences ----------

export const userPreferences = pgTable("user_preferences", {
  user_id: uuid("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  diet: dietEnum("diet").notNull().default("omnivore"),
  dislikes: text("dislikes").array().notNull().default(sql`'{}'::text[]`),
  allergies: text("allergies").array().notNull().default(sql`'{}'::text[]`),
  household_size: integer("household_size").notNull().default(1),
  weekly_budget_chf: numeric("weekly_budget_chf", { precision: 10, scale: 2 }),
  preferred_cuisines: text("preferred_cuisines").array().notNull().default(sql`'{}'::text[]`),
  default_locale: text("default_locale").notNull().default("de-CH"),
  // Retention preferences (mirrors the user's plan answers).
  retain_audio: boolean("retain_audio").notNull().default(true),
  retain_sample_photo_per_item: boolean("retain_sample_photo_per_item").notNull().default(true),
  retain_video_frames: boolean("retain_video_frames").notNull().default(false),
  updated_at: updatedAt(),
});

// ---------- Job queue ----------
// pg-boss owns its own schema; we don't model it here.
